routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/guest', 'GuestController');
Route::resource('/vendor', 'VendorController');
Route::resource('/cost', 'CostController');
Route::resource('/table', 'TableController');
Route::resource('/wedding', 'WeddingController');
Route::resource('/task', 'TaskController');
Route::resource('/vendor_category', 'VendorCategoryController');

app/Vendor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vendor extends Model
{
    //
    protected $guarded = [];
    protected $fillable = [
      'name', 'vendor_category_id', 'email', 'phone_number', 'street_address', 'city', 'postal_code', 'wedding_id'
    ];
    public function wedding()
    {
        return $this->belongsTo(Wedding::class);
    }

    public function vendor_category()
    {
        return $this->belongsTo(VendorCategory::class);
    }
}

app/Http/Controllers/VendorController.php
<?php

namespace App\Http\Controllers;

use App\Vendor;
use App\VendorCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class VendorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $vendors = DB::table('vendors')
            -> join('vendor_categories', 'vendor_category_id', '=', 'vendor_categories.id')
            -> select('vendors.id as id', 'vendors.name as name', 'vendors.email', 'vendors.phone_number',
                'vendors.street_address', 'vendors.postal_code', 'vendors.city',
                'vendor_categories.name as category', 'vendor_categories.icon')
            -> where('vendors.wedding_id', '=', auth()->user()->wedding_id)
            -> orderBy('category')
            -> get();

        $vendor_info = DB::table('vendors')
            -> join('vendor_categories', 'vendor_category_id', '=', 'vendor_categories.id')
            -> select('vendor_categories.name as category', DB::raw('count(*) as categories_count'))
            -> where('vendors.wedding_id', '=', auth()->user()->wedding_id)
            -> groupBy('vendor_categories.name')
            -> orderBy('category')
            -> get();


        if(request()->has('category')){
            $vendors = $vendors->where('category', request('category'));
        }

        return view('vendors.index', compact(['vendors', 'vendor_info']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $vendor_categories = DB::table('vendor_categories')
            ->whereNull('wedding_id')
            ->orWhere('wedding_id', auth()->user()->wedding_id)
            ->get();

        return view('vendors.create', compact(['vendor_categories']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $this->validation();

        $data = array_merge(
          $request->all(),
          ['wedding_id' => auth()->user()->wedding_id]
        );



        Vendor::create($data);
        return redirect()->route('vendor.index')
            ->with('success','Usługodawca został dodany.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function show(Vendor $vendor)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $vendor = Vendor::find($id);

        $selected_category = $vendor->vendor_category_id;

        $vendor_categories = DB::table('vendor_categories')
            ->whereNull('wedding_id')
            ->orWhere('wedding_id', auth()->user()->wedding_id)
            ->get();

        return view('vendors.edit', compact(['vendor', 'selected_category','vendor_categories']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $this->validation();

        $data = array_merge(
            $request->all(),
            ['wedding_id' => auth()->user()->wedding_id]
        );



        $vendor = Vendor::find($id);
        $vendor -> update($data);
        return redirect()->route('vendor.index')
            ->with('success','Usługodawca został edytowany.');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Vendor::find($id)->delete();

        return redirect()->route('vendor.index')
            ->with('success','Usługodawca został usunięty');
    }

    public function validation()
    {
        request()->validate([
            'name' => ['required','unique:vendors,name,NULL,id,wedding_id,'.auth()->user()->wedding_id],
            'email' => 'nullable|email',
            'vendor_category_id' => 'required',
            'phone_number' => '',
            'street_address' => '',
            'postal_code' => '',
            'city' => '',
        ],
            [
                'name.required' => 'Nazwa firmy jest wymagana.',
                'name.unique' => 'Istnieje firma o takiej nazwie',
                'vendor_category_id.required' => 'Wybór kategorii jest wymagany'
            ]
        );
    }
}

resources/views/vendors/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="row">
            <div class="pb-3">

                <a class="btn btn-outline-secondary" href="{{ route('vendor.index') }}"><i
                            class="fas fa-arrow-left"></i> Powrót</a>

            </div>
        </div>

        @if (count($errors) > 0)

            <div class="alert alert-danger">

                <strong>Ups!</strong> Wprowadzone dane są niepoprawne.<br><br>

                <ul>

                    @foreach ($errors->all() as $error)

                        <li>{{ $error }}</li>

                    @endforeach

                </ul>

            </div>

        @endif

        <div class="row">
            <div class="col-md-3 ">

                <h5>Kategorie: </h5>


                <ul class="list-group list-group-flush">
                    {!! Form::open(array('route' => 'vendor_category.store','method'=>'POST')) !!}
                    <li class="list-group-item d-flex justify-content-between align-content-center">
                        {!! Form::text('name', null, array('placeholder' => 'Dodaj kategorie','class' => 'form-control form-control-sm')) !!}
                        <div class="pl-1">
                            <button type="submit" class="btn btn-sm btn-primary"><i class="fas fa-plus"
                                                                                    style="color: white"></i></button>
                        </div>
                    </li>

                    {!! Form::close() !!}
                    @foreach($vendor_categories as $category)
                        <li class="list-group-item d-flex justify-content-between align-content-center">{{ $category ->name }}

                            {!! Form::open(['method' => 'DELETE','route' => ['vendor_category.destroy', $category->id],'style'=>'display:inline']) !!}
                            {!! Form::button('<i class="fas fa-trash "></i>', ['type' => 'submit', 'class' => 'btn btn-link btn-sm']) !!}
                            {!! Form::close() !!}
                        </li>
                    @endforeach

                </ul>

            </div>

            <div class="col-md-9">

                <div align="center">
                    <div class="card w-75">

                        <div class="card-header text-center bg-light">

                            <h3> Dodaj usługodawcę </h3>

                        </div>

                        <div class="card-body">

                            {!! Form::open(array('route' => 'vendor.store','method'=>'POST')) !!}

                            <div class="form-row d-flex align-items-baseline">

                                <div class="form-group col-md-8">

                                    <strong>Firma:</strong>

                                    {!! Form::text('name', null, array('placeholder' => 'Nazwa firmy','class' => 'form-control')) !!}

                                </div>

                                <div class="form-group col-md-4">
                                    <strong>Wybierz kategorie: </strong>
                                    <select name="vendor_category_id" class="custom-select">
                                        @foreach($vendor_categories as $category)
                                            <option value="{{ $category -> id }}">{{ $category -> name }}</option>
                                        @endforeach
                                    </select>
                                </div>

                            </div>

                            <div class="form-row">

                                <div class="form-group col-md-6">

                                    <strong>Email:</strong>

                                    {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}

                                </div>

                                <div class="form-group col-md-6">

                                    <strong>Telefon:</strong>

                                    {!! Form::text('phone_number', null, array('placeholder' => 'Telefon','class' => 'form-control')) !!}

                                </div>

                            </div>

                            <div class="form-row">

                                <div class="form-group col-md-5">

                                    <strong>Adres:</strong>

                                    {!! Form::text('street_address', null, array('placeholder' => 'Adres','class' => 'form-control')) !!}

                                </div>

                                <div class="form-group col-md-3">

                                    <strong>Kod pocztowy:</strong>

                                    {!! Form::text('postal_code', null, array('placeholder' => 'Kod pocztowy','class' => 'form-control')) !!}

                                </div>

                                <div class="form-group col-md-4">

                                    <strong>Miejscowość:</strong>

                                    {!! Form::text('city', null, array('placeholder' => 'Miejscowość','class' => 'form-control')) !!}

                                </div>

                            </div>

                            <div class="col-md-12 text-center">

                                <button type="submit" class="btn btn-primary">Zapisz</button>

                            </div>

                            {!! Form::close() !!}</div>
                    </div>
                </div>


            </div>
        </div>

    </div>


@endsection

resources/views/vendors/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="pb-3">

                    <a class="btn btn-outline-secondary" href="{{ route('vendor.index') }}"><i class="fas fa-arrow-left"></i> Powrót</a>

                </div>

                <div class="card">

                    <div class="card-header text-center bg-light">

                        <h3> Edytuj usługodawcę </h3>

                    </div>

                    <div class="card-body">

                        {!! Form::model($vendor, ['method' => 'PATCH','route' => ['vendor.update', $vendor->id]]) !!}

                        <div class="form-row d-flex align-items-baseline">

                            <div class="form-group col-md-8">

                                <strong>Firma:</strong>

                                {!! Form::text('name', null, array('placeholder' => 'Nazwa firmy','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-4">
                                <strong>Wybierz kategorie: </strong>
                                <select name="vendor_category_id" class="custom-select">
                                    @foreach($vendor_categories as $category)
                                        <option {{ $selected_category == $category -> id ? 'selected' : '' }} value="{{ $category -> id }}">
                                            {{ $category -> name }}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                        </div>

                        <div class="form-row">

                            <div class="form-group col-md-6">

                                <strong>Email:</strong>

                                {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-6">

                                <strong>Telefon:</strong>

                                {!! Form::text('phone_number', null, array('placeholder' => 'Telefon','class' => 'form-control')) !!}

                            </div>

                        </div>

                        <div class="form-row">

                            <div class="form-group col-md-5">

                                <strong>Adres:</strong>

                                {!! Form::text('street_address', null, array('placeholder' => 'Adres','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-3">

                                <strong>Kod pocztowy:</strong>

                                {!! Form::text('postal_code', null, array('placeholder' => 'Kod pocztowy','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-4">

                                <strong>Miejscowość:</strong>

                                {!! Form::text('city', null, array('placeholder' => 'Miejscowość','class' => 'form-control')) !!}

                            </div>

                        </div>

                        <div class="col-md-12 text-center">

                            <button type="submit" class="btn btn-primary">Edytuj</button>

                        </div>

                        {!! Form::close() !!}</div>
                </div>
            </div>


        </div>
    </div>

@endsection

resources/views/vendors/index.blade.php
@extends('layouts.app')

@section('content')
    <div class='container'>


        <div class="row">
            <div class="col-md-3">
                <h5>Kategorie: </h5>

                @foreach($vendor_info as $info)
                    <ul class="list-group list-group-flush">

                        <a href="/vendor/?category={{ $info -> category }}"
                           class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">{{ $info -> category }}
                            <span class="badge badge-primary badge-pill">{{ $info -> categories_count }}</span>
                        </a>
                    </ul>
                @endforeach


                <div class="pt-1">
                    <a href="/vendor">Wyczyść filtry</a>
                </div>
            </div>

            <div class="col-9">

                <div class="row justify-content-center pb-3">

                    <a class="btn btn-primary btn-lg cl-white" href="{{ route('vendor.create') }}"><i
                                class="fas fa-plus" style="color: white"></i> Dodaj usługodawcę</a>

                </div>

                <div class="row justify-content-center">
                    @foreach($vendors as $vendor)

                        <div class="col-md-4 col-12 pb-4">

                            <div class="card">

                                <div class="card-header card-vendor-background">

                                    <div class="text-center"><i class="{{ $vendor -> icon }} fa-2x"> </i></div>

                                    <h4 class="card-title text-center">{{ $vendor -> category }}</h4>

                                </div>

                                <div class="card-body">


                                    <h6 class="card-subtitle mb-2"><strong>Firma: </strong>{{ $vendor -> name }}</h6>

                                    <p class="card-text"><i
                                                class="fas fa-map-marker-alt"></i> {{ $vendor -> street_address }} <br>

                                        {{$vendor->postal_code}} {{ $vendor ->city }} </p>

                                    <p><i class="fas fa-phone"></i> {{ $vendor -> phone_number }}</p>

                                    <p><i class="fas fa-at"></i> {{ $vendor -> email }}</p>

                                    <div class="d-flex justify-content-between">
                                        <a class="btn btn-sm btn-link" href="{{ route('vendor.edit',$vendor->id) }}">Edytuj</a>
                                        {!! Form::open(['method' => 'DELETE','route' => ['vendor.destroy', $vendor->id],'style'=>'display:inline']) !!}
                                        {!! Form::button('Usuń', ['type' => 'submit', 'class' => 'btn btn-sm btn-link']) !!}
                                        {!! Form::close() !!}
                                    </div>

                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>

@endsection