routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/guest', 'GuestController');
Route::resource('/vendor', 'VendorController');
Route::resource('/cost', 'CostController');
Route::resource('/table', 'TableController');
Route::resource('/wedding', 'WeddingController');
Route::resource('/task', 'TaskController');
Route::resource('/vendor_category', 'VendorCategoryController');

app/Guest.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Guest extends Model
{
    protected $guarded = [];

    protected $fillable = [
        'name', 'surname', 'age', 'email', 'phone_number', 'street_address', 'city', 'postal_code',
        'confirmation', 'accommodation', 'transport', 'special_diet', 'party', 'note', 'wedding_id'
    ];

    public function wedding()
    {
        return $this->belongsTo(Wedding::class);
    }

    public function table()
    {
        return $this->belongsTo(Table::class);
    }
}

app/Http/Controllers/GuestController.php
<?php

namespace App\Http\Controllers;

use App\Guest;
use App\Wedding;
use Illuminate\Http\Request;

class GuestController extends Controller
{

    public function _construct() {

        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $guests = Guest::where('wedding_id','=', auth()->user()->wedding_id);
        $all_guests = Guest::where('wedding_id','=', auth()->user()->wedding_id)->count();
        $filtered_guests = $all_guests;
        $queries = [];

        $columns = [
          'confirmation',
          'special_diet',
          'accommodation',
          'transport',
          'party'
        ];

        foreach ($columns as $column){

            if(request()->has($column)) {
                $guests = $guests->where($column, request($column));
                $filtered_guests = $guests->where($column, request($column))->count();
                $queries[$column] = request($column);
            }
        }

        $guests = $guests->paginate(10)->appends($queries);

        return view('guests.index',compact(['guests', 'all_guests', 'filtered_guests']))
            ->with('i', ($request->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('guests.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validation();

        $confirmation = isset($request->confirmation) ? 1 : 0;
        $accommodation = isset($request->accommodation) ? 1 : 0;
        $special_diet = isset($request->special_diet) ? 1 : 0;
        $transport = isset($request->transport) ? 1 : 0;


        $data = array_merge(
            $request->all(),
            ['wedding_id' => auth()->user()->wedding_id],
            ['confirmation' => $confirmation],
            ['accommodation' => $accommodation],
            ['special_diet' => $special_diet],
            ['transport' => $transport]
        );

        Guest::create($data);
        return redirect()->route('guest.index')
            ->with('success','Gość został dodany.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Guest  $guest
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        $guest = Guest::find($id);
        $age = $guest->age == 1 ? 'Dorosły' : 'Dziecko';

        if($guest->party == 'her')
            $party = 'Panna Młoda';
        elseif($guest->party == 'his')
            $party = 'Pan Młody';
        else
            $party = 'Wspólny';

        $confirmationCheck = $guest->confirmation == 1 ? 'checked' : '';
        $special_dietCheck = $guest->special_diet == 1 ? 'checked' : '';
        $accommodationCheck = $guest->accommodation == 1 ? 'checked' : '';
        $transportCheck = $guest->transport == 1 ? 'checked' : '';

        return view('guests.show', compact([
            'guest',
            'age',
            'party',
            'confirmationCheck',
            'special_dietCheck',
            'accommodationCheck',
            'transportCheck',
        ]));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Guest  $guest
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $guest = Guest::find($id);

        $confirmationCheck = $guest->confirmation == 1 ? 'checked' : '';
        $special_dietCheck = $guest->special_diet == 1 ? 'checked' : '';
        $accommodationCheck = $guest->accommodation == 1 ? 'checked' : '';
        $transportCheck = $guest->transport == 1 ? 'checked' : '';

        return view('guests.edit', compact([
            'guest',
            'confirmationCheck',
            'special_dietCheck',
            'accommodationCheck',
            'transportCheck',
        ]));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Guest  $guest
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $this->validation();


        $confirmation = isset($request->confirmation) ? 1 : 0;
        $accommodation = isset($request->accommodation) ? 1 : 0;
        $special_diet = isset($request->special_diet) ? 1 : 0;
        $transport = isset($request->transport) ? 1 : 0;


        $data = array_merge(
            $request->all(),
            ['wedding_id' => auth()->user()->wedding_id],
            ['confirmation' => $confirmation],
            ['accommodation' => $accommodation],
            ['special_diet' => $special_diet],
            ['transport' => $transport]
        );

        $guest = Guest::find($id);
        $guest->update($data);

        return redirect()->route('guest.index')
            ->with('success','Gość został edytowany.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Guest  $guest
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Guest::find($id)->delete();

        return redirect()->route('guest.index')
            ->with('success','Gość został usunięty');
    }

    public function validation()
    {
        request()->validate([
            'name' => 'required',
            'surname' => 'required',
            'age' => '',
            'email' => 'nullable|email',
            'phone_number' => '',
            'street_address' => '',
            'postal_code' => '',
            'city' => '',
            'party' => '',
            'confirmation' => '',
            'accommodation' => '',
            'special_diet' => '',
            'transport' => '',
            'note' => ''
        ],
            [
                'name.required' => 'Imię jest wymagane.',
                'surname.required' => 'Nazwisko jest wymagane.',
                'email' => 'Niepoprawny format email.'
            ]
        );
    }
}

resources/views/guests/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="pb-3">

                    <a class="btn btn-outline-secondary" href="{{ route('guest.index') }}"><i class="fas fa-arrow-left"></i> Powrót</a>

                </div>

                @if (count($errors) > 0)

                    <div class="alert alert-danger">

                        <strong>Ups!</strong> Wprowadzone dane są niepoprawne.<br><br>

                        <ul>

                            @foreach ($errors->all() as $error)

                                <li>{{ $error }}</li>

                            @endforeach

                        </ul>

                    </div>

                @endif


                <div class="card">

                    <div class="card-header text-center bg-white">

                        <h3> Dodaj gościa </h3>

                    </div>

                    <div class="card-body">

                        {!! Form::open(array('route' => 'guest.store','method'=>'POST')) !!}

                        <h4>Dane personalne</h4>

                        <div class="form-row d-flex align-items-baseline">

                            <div class="form-group col-md-5">

                                <strong>Imię:</strong>

                                {!! Form::text('name', null, array('placeholder' => 'Imię','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-5">

                                <strong>Nazwisko:</strong>

                                {!! Form::text('surname', null, array('placeholder' => 'Nazwisko','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-2">

                                <strong>Wiek:</strong>

                                <div>{!! Form::select('age', array('1' => 'Dorosły', '0' => 'Dziecko'), null, array('class' => 'custom-select')) !!} </div>
                            </div>

                        </div>

                        <h4 class="pt-3">Dane kontaktowe</h4>

                        <div class="form-row">

                            <div class="form-group col-md-6">

                                <strong>Email:</strong>

                                {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-6">

                                <strong>Telefon:</strong>

                                {!! Form::text('phone_number', null, array('placeholder' => 'Telefon','class' => 'form-control')) !!}

                            </div>

                        </div>

                        <div class = "form-row">

                            <div class ="form-group col-md-5">

                                <strong>Adres:</strong>

                                {!! Form::text('street_address', null, array('placeholder' => 'Adres','class' => 'form-control')) !!}

                            </div>

                            <div class ="form-group col-md-3">

                                <strong>Kod pocztowy:</strong>

                                {!! Form::text('postal_code', null, array('placeholder' => 'Kod pocztowy','class' => 'form-control')) !!}

                            </div>

                            <div class ="form-group col-md-4">

                                <strong>Miejscowość:</strong>

                                {!! Form::text('city', null, array('placeholder' => 'Miejscowość','class' => 'form-control')) !!}

                            </div>


                        </div>

                        <h4 class="pt-3">Pozostałe informacje</h4>

                        <div class="form-row">

                            <div class="form-group col-md-3">

                                <strong>Zapraszający:</strong>

                                <div>{!! Form::select('party', array('both' => 'Wspólny', 'her' => 'Panna Młoda', 'his' => 'Pan Młody'), null, array('class' => 'custom-select')) !!} </div>

                            </div>


                        </div>


                        <div class="form-row">

                            <div class="custom-control custom-checkbox form-check-inline">

                                <input type="checkbox" class="custom-control-input" id="confirmation" name="confirmation" value="1">
                                <label class="custom-control-label" for="confirmation">Przybycie</label>

                            </div>


                            <div class="custom-control custom-checkbox form-check-inline">

                                <input type="checkbox" class="custom-control-input" id="special_diet" name="special_diet" value="1">
                                <label class="custom-control-label" for="special_diet">Dieta</label>

                            </div>

                            <div class="custom-control custom-checkbox form-check-inline">

                                <input type="checkbox" class="custom-control-input" id="accommodation" name="accommodation" value="1">
                                <label class="custom-control-label" for="accommodation">Nocleg</label>

                            </div>

                            <div class="custom-control custom-checkbox form-check-inline">

                                <input type="checkbox" class="custom-control-input" id="transport" name="transport" value="1">
                                <label class="custom-control-label" for="transport">Transport</label>

                            </div>

                        </div>

                        <div class="form-row pt-2">

                            <div class="form-group col-md-12">

                                <strong>Notatka:</strong>

                                <textarea class="form-control" id="note" name="note" rows="2"> {{ old('note') }} </textarea>

                            </div>

                        </div>

                        <div class="col-md-12 text-center">

                            <button type="submit" class="btn btn-primary">Zapisz</button>

                        </div>
                        {!! Form::close() !!}</div>
                </div>
            </div>
        </div>
        </div></div>


@endsection

resources/views/guests/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="pb-3">

                    <a class="btn btn-outline-secondary" href="{{ route('guest.index') }}"><i class="fas fa-arrow-left"></i> Powrót</a>

                </div>

                @if (count($errors) > 0)

                    <div class="alert alert-danger">

                        <strong>Whoops!</strong> There were some problems with your input.<br><br>

                        <ul>

                            @foreach ($errors->all() as $error)

                                <li>{{ $error }}</li>

                            @endforeach

                        </ul>

                    </div>

                @endif


                <div class="card">

                    <div class="card-header text-center bg-white">

                        <h3> Edytuj gościa </h3>

                    </div>

                    <div class="card-body">

                        {!! Form::model($guest, ['method' => 'PATCH','route' => ['guest.update', $guest->id]]) !!}

                        <h4>Dane personalne</h4>

                        <div class="form-row d-flex align-items-baseline">

                            <div class="form-group col-md-5">

                                <strong>Imię:</strong>

                                {!! Form::text('name', null, array('placeholder' => 'Imię','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-5">

                                <strong>Nazwisko:</strong>

                                {!! Form::text('surname', null, array('placeholder' => 'Nazwisko','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-2">

                                <strong>Wiek:</strong>

                                <div>{!! Form::select('age', array('1' => 'Dorosły', '0' => 'Dziecko'), null, array('class' => 'custom-select')) !!} </div>
                            </div>

                        </div>

                        <h4 class="pt-3">Dane kontaktowe</h4>

                        <div class="form-row">

                            <div class="form-group col-md-6">

                                <strong>Email:</strong>

                                {!! Form::text('email', null, array('placeholder' => 'Email','class' => 'form-control')) !!}

                            </div>

                            <div class="form-group col-md-6">

                                <strong>Telefon:</strong>

                                {!! Form::text('phone_number', null, array('placeholder' => 'Telefon','class' => 'form-control')) !!}

                            </div>

                        </div>

                        <div class = "form-row">

                            <div class ="form-group col-md-5">

                                <strong>Adres:</strong>

                                {!! Form::text('street_address', null, array('placeholder' => 'Adres','class' => 'form-control')) !!}

                            </div>

                            <div class ="form-group col-md-3">

                                <strong>Kod pocztowy:</strong>

                                {!! Form::text('postal_code', null, array('placeholder' => 'Kod pocztowy','class' => 'form-control')) !!}

                            </div>

                            <div class ="form-group col-md-4">

                                <strong>Miejscowość:</strong>

                                {!! Form::text('city', null, array('placeholder' => 'Miejscowość','class' => 'form-control')) !!}

                            </div>


                        </div>

                        <h4 class="pt-3">Pozostałe informacje</h4>

                        <div class="form-row">

                            <div class="form-group col-md-3">

                                <strong>Zapraszający:</strong>

                                <div>{!! Form::select('party', array('both' => 'Wspólny', 'her' => 'Panna Młoda', 'his' => 'Pan Młody'), null, array('class' => 'custom-select')) !!} </div>

                            </div>


                        </div>


                        <div class="form-row">

                            <div class="custom-control custom-checkbox form-check-inline">

                                <input type="checkbox" class="custom-control-input" id="confirmation" name="confirmation" value="1" {{ $confirmationCheck }}>
                                <label class="custom-control-label" for="confirmation">Przybycie</label>

                            </div>


                            <div class="custom-control custom-checkbox form-check-inline">

                                <input type="checkbox" class="custom-control-input" id="special_diet" name="special_diet" value="1" {{ $special_dietCheck }}>
                                <label class="custom-control-label" for="special_diet">Dieta</label>

                            </div>

                            <div class="custom-control custom-checkbox form-check-inline">

                                <input type="checkbox" class="custom-control-input" id="accommodation" name="accommodation" value="1" {{ $accommodationCheck }}>
                                <label class="custom-control-label" for="accommodation">Nocleg</label>

                            </div>

                            <div class="custom-control custom-checkbox form-check-inline">

                                <input type="checkbox" class="custom-control-input" id="transport" name="transport" value="1" {{ $transportCheck }}>
                                <label class="custom-control-label" for="transport">Transport</label>

                            </div>

                        </div>

                        <div class="form-row pt-2">

                            <div class="form-group col-md-12">

                                <strong>Notatka:</strong>

                                <textarea class="form-control" id="note" name="note" rows="2">{{ $guest->note }}</textarea>

                            </div>

                        </div>

                        <div class="col-md-12 text-center">

                            <button type="submit" class="btn btn-primary">Edytuj</button>

                        </div>
                        {!! Form::close() !!}</div>
                </div>
            </div>
        </div>
    </div></div>


@endsection

resources/views/guests/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">



        <div class="row justify-content-between d-flex align-items-baseline pb-1">

            <div class="row">

                <div class="dropdown pl-1">
                    <button class="btn btn-outline-secondary btn-sm dropdown-toggle {{ (request()->has('confirmation')) ? 'active' : '' }}"
                            type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Przybycie
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/guest/?confirmation=1">Potwierdzone</a>
                        <a class="dropdown-item" href="/guest/?confirmation=0">Nie potwierdzone</a>
                    </div>
                </div>

                <div class="dropdown pl-1">
                    <button class="btn btn-outline-secondary btn-sm dropdown-toggle {{ (request()->has('special_diet')) ? 'active' : '' }} "
                            type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dieta
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/guest/?special_diet=1">Dieta specjalna</a>
                        <a class="dropdown-item" href="/guest/?special_diet=0">Brak diety</a>
                    </div>
                </div>

                <div class="dropdown pl-1">
                    <button class="btn btn-outline-secondary btn-sm dropdown-toggle {{ (request()->has('accommodation')) ? 'active' : '' }} "
                            type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Nocleg
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/guest/?accommodation=1">Wymagany</a>
                        <a class="dropdown-item" href="/guest/?accommodation=0">Nie wymagany</a>
                    </div>
                </div>

                <div class="dropdown pl-1">
                    <button class="btn btn-outline-secondary btn-sm dropdown-toggle {{ (request()->has('transport')) ? 'active' : '' }} "
                            type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Transport
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/guest/?transport=1">Wymagany</a>
                        <a class="dropdown-item" href="/guest/?transport=0">Nie wymagany</a>
                    </div>
                </div>

                <div class="dropdown pl-1">
                    <button class="btn btn-outline-secondary btn-sm dropdown-toggle {{ (request()->has('party')) ? 'active' : '' }} "
                            type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Zapraszający
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/guest/?party=both">Wspólny</a>
                        <a class="dropdown-item" href="/guest/?party=her">Panna Młoda</a>
                        <a class="dropdown-item" href="/guest/?party=his">Pan Młody</a>
                    </div>
                </div>

                <div class="pl-1">
                    <a class="btn btn-outline-primary btn-sm " href="/guest">Wyczyść filtry</a>
                </div>

            </div>

            <a class="btn btn-primary btn-lg" href="{{ route('guest.create') }}" style="color:white">
                <i class="fas fa-plus" style="color: white"></i> Dodaj gościa</a>

        </div>



        @if ($message = Session::get('success'))

            <div class="alert alert-success">

                <p>{{ $message }}</p>

            </div>

        @endif

        <div class="row justify-content-center pt-1">
            <div class="col-md-12 table-responsive">
                <table class="table table-hover">

                    <thead>
                        <tr>

                            <th>Lp.</th>

                            <th>Imię i nazwisko</th>

                            <th class="text-center">Przybycie</th>

                            <th class="text-center">Dieta</th>

                            <th class="text-center">Nocleg</th>

                            <th class="text-center">Transport</th>

                            <th class="text-center">Zapraszający</th>

                            <th class="text-center">Opcje</th>

                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($guests as $key => $guest)

                            <tr>

                                <td>{{ ++$i }}</td>

                                <td>{{ $guest->name }} {{ $guest->surname }} </td>

                                <td class="party text-center">

                                    <i class="fas fa-check-circle fa-lg" {{ intval($guest->confirmation) == 1 ? 'style=color:yellowgreen' : '' }}></i>

                                </td>

                                <td class="party text-center">

                                        <i class="fas fa-utensils fa-lg" {{ intval($guest->special_diet) == 1 ? 'style=color:yellowgreen' : '' }}> </i>

                                </td>

                                <td class="party text-center">

                                        <i class="fas fa-bed fa-lg" {{ intval($guest->accommodation) == 1 ? 'style=color:yellowgreen' : '' }}> </i>

                                </td>

                                <td class="party text-center">

                                        <i class="fas fa-car fa-lg" {{ intval($guest->transport) == 1 ? 'style=color:yellowgreen' : '' }}> </i>

                                </td>

                                <td class="party text-center">
                                    @if($guest->party == 'her')
                                        <i class="fas fa-female fa-lg" style="color:pink"> </i>
                                    @elseif($guest->party == 'his')
                                        <i class="fas fa-male fa-lg" style="color:cornflowerblue"> </i>
                                    @else
                                        <i class="fas fa-female fa-lg" style="color:pink"></i><i class="fas fa-male fa-lg" style="color:cornflowerblue"> </i>
                                    @endif
                                </td>

                                <td class="text-center">

                                    <a class="btn btn-sm btn-info" href="{{ route('guest.show',$guest->id) }}"><i class="fas fa-search" style="color: white"></i></a>

                                    <a class="btn btn-sm btn-primary" href="{{ route('guest.edit',$guest->id) }}"><i class="fas fa-edit" style="color: white"></i></a>

                                    {!! Form::open(['method' => 'DELETE','route' => ['guest.destroy', $guest->id],'style'=>'display:inline']) !!}

                                    {!! Form::button('<i class="fas fa-trash" style="color: white"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-danger']) !!}

                                    {!! Form::close() !!}

                                </td>

                            </tr>

                        @endforeach
                    </tbody>

                </table>

                <div class="row">
                    <p class="text-muted">Liczba gości: {{ $filtered_guests }} z {{ $all_guests }}</p>
                </div>

            </div>
        </div>


        <div class="row justify-content-center">

                {{ $guests->links() }}

        </div>

    </div>



@endsection