routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/guest', 'GuestController');
Route::resource('/vendor', 'VendorController');
Route::resource('/cost', 'CostController');
Route::resource('/table', 'TableController');
Route::resource('/wedding', 'WeddingController');
Route::resource('/task', 'TaskController');
Route::resource('/vendor_category', 'VendorCategoryController');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
    protected $guarded = [];
    protected $fillable = [
        'title', 'note', 'due_date_planned', 'wedding_id', 'status'
    ];

    public function wedding(){

        return $this->belongsTo(Wedding::class);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $overdue_tasks = Task::orderBy('due_date_planned')
            ->where('wedding_id', '=', auth()->user()->wedding_id)
            ->where('status', '=', '1')
            ->get();


        $tasks = Task::orderBy('due_date_planned')
            ->where('wedding_id','=', auth()->user()->wedding_id)
            ->where('status', '=', '0')
            ->get()
            ->groupBy(function($item) {
                 return Carbon::parse($item->due_date_planned)->format('m-Y');
        });


        return view('tasks.index', compact(['tasks', 'overdue_tasks']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('tasks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        request()->validate([
            'title' => ['required','unique:tasks,title,NULL,id,wedding_id,'.auth()->user()->wedding_id],
            'due_date_planned' => 'required'

        ],
            [
                'title.required' => 'Nazwa zadania jest wymagana.',
                'due_date_planned.required' => 'Wybór daty jest wymagany',
                'title.unique' => 'Istnieje już takie zadanie'
            ]
        );

        $data = array_merge(
            $request->all(),
            ['wedding_id' => auth()->user()->wedding_id]
        );



        Task::create($data);
        return redirect()->route('task.index')
            ->with('success','Zadanie zostało dodane.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        $task = Task::find($id);

        return view('tasks.show', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);

        return view('tasks.edit', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        //dd($task);

       if($request->has('title')){
           request()->validate([
               'title' => ['required','unique:tasks,title,'.$task->id.',id,wedding_id,'.auth()->user()->wedding_id],
               'due_date_planned' => 'required'

           ],
               [
                   'title.required' => 'Nazwa zadania jest wymagana.',
                   'due_date_planned.required' => 'Wybór daty jest wymagany',
                   'title.unique' => 'Istnieje już takie zadanie'
               ]
           );

       }

        $task->update($request->all());

        return redirect()->route('task.index');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        Task::find($id)->delete();

        return redirect()->route('task.index')
            ->with('success','Zadanie zostało usunięte');
    }

}

resources/views/tasks/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="pb-3">

                    <a class="btn btn-outline-secondary" href="{{ route('task.index') }}"><i class="fas fa-arrow-left"></i> Powrót</a>

                </div>

                @if (count($errors) > 0)

                    <div class="alert alert-danger">

                        <strong>Ups!</strong> Wprowadzone dane są niepoprawne.<br><br>

                        <ul>

                            @foreach ($errors->all() as $error)

                                <li>{{ $error }}</li>

                            @endforeach

                        </ul>

                    </div>

                @endif


                <div class="card">

                    <div class="card-header text-center bg-white">

                        <h3> Dodaj zadanie </h3>

                    </div>

                    <div class="card-body">

                        {!! Form::open(array('route' => 'task.store','method'=>'POST')) !!}


                        <div class="form-row">

                            <div class="form-group col-12">

                                <strong>Nazwa zadania:</strong>

                                {!! Form::text('title', null, array('placeholder' => 'Nazwa zadania','class' => 'form-control')) !!}

                            </div>

                        </div>

                        <div class="form-row">

                            <div class="form-group col-12">

                                <strong>Data wykonania:</strong>

                                {!! Form::date('due_date_planned', null, array('placeholder' => 'Nazwa zadania','class' => 'form-control')) !!}

                            </div>

                        </div>

                        <div class="form-row pt-2">

                            <div class="form-group col-12">

                                <strong>Notatka:</strong>

                                <textarea class="form-control" id="note" name="note" rows="2"> {{ old('note') }} </textarea>

                            </div>

                        </div>


                        <div class=" text-center pt-2">

                            <button type="submit" class="btn btn-primary">Zapisz</button>

                        </div>
                        {!! Form::close() !!}</div>
                </div>
            </div>
        </div>
    </div>
    </div>




@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="pb-3">

                    <a class="btn btn-outline-secondary" href="{{ route('task.index') }}"><i class="fas fa-arrow-left"></i> Powrót</a>

                </div>

                @if (count($errors) > 0)

                    <div class="alert alert-danger">

                        <strong>Ups!</strong> Wprowadzone dane są niepoprawne.<br><br>

                        <ul>

                            @foreach ($errors->all() as $error)

                                <li>{{ $error }}</li>

                            @endforeach

                        </ul>

                    </div>

                @endif


                <div class="card">

                    <div class="card-header text-center bg-white">

                        <h3> Edytuj zadanie </h3>

                    </div>

                    <div class="card-body">

                        {!! Form::model($task, ['method' => 'PATCH','route' => ['task.update', $task->id]]) !!}


                        <div class="form-row">

                            <div class="form-group col-12">

                                <strong>Nazwa zadania:</strong>

                                {!! Form::text('title', null, array('placeholder' => 'Nazwa zadania','class' => 'form-control')) !!}

                            </div>

                        </div>

                        <div class="form-row">

                            <div class="form-group col-12">

                                <strong>Data wykonania:</strong>

                                {!! Form::date('due_date_planned', null, array('placeholder' => 'Nazwa zadania','class' => 'form-control')) !!}

                            </div>

                        </div>

                        <div class="form-row pt-2">

                            <div class="form-group col-12">

                                <strong>Notatka:</strong>

                                <textarea class="form-control" id="note" name="note" rows="2"> {{ $task->note }} </textarea>

                            </div>

                        </div>


                        <div class=" text-center pt-2">

                            <button type="submit" class="btn btn-primary">Zapisz</button>

                        </div>
                        {!! Form::close() !!}</div>
                </div>
            </div>
        </div>
    </div></div>


@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">

        <div class="row justify-content-center pb-3">

            <a class="btn btn-primary btn-lg cl-white" href="{{ route('task.create') }}"><i class="fas fa-plus"
                                                                                            style="color: white"></i>
                Dodaj zadanie</a>

        </div>


        <div class="col-md-12"><h4 class="pt-4">Zrealizowane</h4>

            <ui class="list-group">
                @foreach ($overdue_tasks as $overdue_task)

                    <li class="list-group-item d-flex flex-column">
                        <div class="row d-flex justify-content-between">
                            <div>
                                <div class="custom-control custom-checkbox form-check-inline">

                                    <input type="checkbox" class="custom-control-input" id="{{ $overdue_task->id }}"
                                           name="status" value="0" checked>
                                    <label class="custom-control-label"
                                           for="{{$overdue_task->id}}"><del>{{ $overdue_task->title }}</del></label>

                                </div>
                            </div>

                            {!! Form::open(['method' => 'DELETE','route' => ['task.destroy', $overdue_task->id],'style'=>'display:inline']) !!}
                            {!! Form::button('<i class="fas fa-trash "></i>', ['type' => 'submit', 'class' => 'btn btn-link btn-sm']) !!}
                            {!! Form::close() !!}

                        </div>
                        <div class="text-muted">{{ $overdue_task->due_date_planned }}
                            <a class="btn btn-sm btn-link" href="{{ route('task.show',$overdue_task->id) }}">Pokaż</a>
                            <a class="btn btn-sm btn-link" href="{{ route('task.edit',$overdue_task->id) }}">Edytuj</a>
                        </div>

                    </li>
                @endforeach
            </ui>
        </div>


        @foreach ($tasks as $time => $tasks_list)
            <div class="col-md-12"><h4 class="pt-4">{{ $time }} </h4>

                <ui class="list-group">
                    @foreach ($tasks_list as $task)

                        <li class="list-group-item d-flex flex-column">
                            <div class="row d-flex justify-content-between">
                                <div>
                                    <div class="custom-control custom-checkbox form-check-inline">

                                        <input type="checkbox" class="custom-control-input" id="{{ $task->id }}"
                                               name="status" value="1" >
                                        <label class="custom-control-label"
                                               for="{{$task->id}}">{{ $task->title }}</label>

                                    </div>
                                </div>

                                {!! Form::open(['method' => 'DELETE','route' => ['task.destroy', $task->id],'style'=>'display:inline']) !!}
                                {!! Form::button('<i class="fas fa-trash "></i>', ['type' => 'submit', 'class' => 'btn btn-link btn-sm']) !!}
                                {!! Form::close() !!}

                            </div>
                            <div class="text-muted">{{ $task->due_date_planned }}
                                <a class="btn btn-sm btn-link" href="{{ route('task.show',$task->id) }}">Pokaż</a>
                                <a class="btn btn-sm btn-link" href="{{ route('task.edit',$task->id) }}">Edytuj</a>
                            </div>
                        </li>
                    @endforeach
                </ui>
            </div>
        @endforeach

    </div>

    <script src="http://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous">
    </script>


    <script>
        jQuery(document).ready(function(){

            jQuery("input[type='checkbox']").change(function(){

                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    }
                });
                let patch = "{{ url('/task') }}" + '/' + $(this).attr('id');
                $.ajax({
                    url: patch  ,
                    method: 'patch',
                    data: {
                        'status' : $(this).is(':checked') ? 1 : 0

                    },
                    success: function(result){
                        console.log(result);

                    },
                    complete: function (result) {
                        location.reload();
                    }
                });

            });


        });


    </script>

@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')


@section('content')
    <div class="container">

        <div class="row justify-content-center">

            <div class="col-md-8">

                <div class="pb-3">

                    <a class="btn btn-outline-secondary" href="{{ route('task.index') }}"><i class="fas fa-arrow-left"></i> Powrót</a>

                </div>

                @if (count($errors) > 0)

                    <div class="alert alert-danger">

                        <strong>Ups!</strong> Wprowadzone dane są niepoprawne.<br><br>

                        <ul>

                            @foreach ($errors->all() as $error)

                                <li>{{ $error }}</li>

                            @endforeach

                        </ul>

                    </div>

                @endif


                <div class="card">

                    <div class="card-header text-center bg-white">

                        <h3> Twoje zadanie </h3>

                    </div>

                    <div class="card-body">

                        <div class="form-row">

                            <div class="form-group col-12">

                                <strong>Nazwa zadania:</strong>
                                {{ $task -> title }}

                            </div>

                        </div>

                        <div class="form-row">

                            <div class="form-group col-12">

                                <strong>Data wykonania:</strong>

                                {{ $task -> due_date_planned }}

                            </div>

                        </div>

                        <div class="form-row pt-2">

                            <div class="form-group col-12">

                                <strong>Notatka:</strong>

                                <textarea disabled class="form-control bg-white" id="note" name="note" rows="2"> {{ $task->note }} </textarea>

                            </div>

                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div></div>


@endsection